# Generated by Django 2.1 on 2018-08-18 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facesigneture',
            name='signeture',
        ),
        migrations.AddField(
            model_name='facesigneture',
            name='face',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='facesigneture',
            name='signetures',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='facesigneture',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
