# Generated by Django 2.1 on 2018-08-21 09:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recognition', '0002_auto_20180818_1953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaceSigneture',
            new_name='FaceSignature',
        ),
        migrations.RenameField(
            model_name='facesignature',
            old_name='signetures',
            new_name='signatures',
        ),
    ]
